Assignments/boolean birds
bhs-intro-to-programming/AWalnut1 pull request #1
Opened 2022-09-09 21:59 UTC by AWalnut1

2022-09-10 03:38 UTC, gigamonkey requested changes
Like I said in one of the comments below, I love to see you working at these problems. Maybe with the hint I gave you about `isRed`, you can finish out these problems. But nice work so far!

2022-09-10 03:38 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +const isRed = (bird) => {
Looking at the history of your work on this function I can see you trying lots of things. I know it must have been frustrating but actually like to see you working at it. And you got *so* close. At one point you had this:

```
  return bird === 'Flobby' && bird === 'Bloggy'
```

That is exactly the right idea: each expression with an `===` produces a boolean value (i.e. `bird === 'Flobby'` is one boolean, a.k.a.`true` or `false` and likewise `bird === 'Bloggy'`). Then you need to combine those two booleans to get a final boolean answer. The only problem is that a bird is red if it's a Flobby Bird *or* a Bloggy Bird, so it should have been:

```
  return bird === 'Flobby' || bird === 'Bloggy'
```

(It may be worth thinking about for a minute why `bird === 'Flobby' && bird === 'Bloggy'` will always be `false`: one value, `bird` can't be equal to two different values at the same time.)

2022-09-13 22:07 UTC, AWalnut1 commented
hey I finished it.
im not really sure if this is how im supposed to submit secondary pull requests but doesnt hurt to try.
thanks for the comment by the way, its encouraging to see you enjoying my suffering.
and the help was nice too, would have been nice to see it before my neighbor helped me, but it did help me truly understand why thats the way it is.

2022-09-16 00:10 UTC, gigamonkey approved these changes
Looks good. Ready to merge.

2022-09-16 06:30 UTC, merged