Assignments/number functions
bhs-intro-to-programming/AWalnut1 pull request #2
Opened 2022-09-09 22:02 UTC by AWalnut1

cool stuff, was fun.

2022-09-10 03:29 UTC, gigamonkey requested changes
Overall looks good! However I would like you to switch to the other form of function definition. Then I'll re-review and most likely approve this to be merged.

2022-09-10 03:29 UTC, gigamonkey commented on assignments/number-functions/code.js
> +function add (a,b) {
Lots of kids seem to have picked up this syntax somewhere. Which is fine: it's legal Javascript. However I'm trying to teach you a slightly different syntax and want you to get comfortable with it.

```suggestion
const add = (a, b) => {
```

Can you convert these functions to that syntax to make sure you're comfortable with it?

2022-09-13 21:46 UTC, AWalnut1 commented on assignments/number-functions/code.js
> +function add (a,b) {
done, sorry i havent seen this untill today

2022-09-16 00:09 UTC, gigamonkey approved these changes
Whoops. Missed that you had updated. This is ready to merge.

2022-09-16 06:31 UTC, merged