Did the things you asked
bhs-intro-to-programming/AWalnut1 pull request #29
Opened 2023-01-18 23:31 UTC by AWalnut1

Got the Dynamic Web Page thing up and running, about half way done, got a bit snagged on getting lists to work but im sure I'll be able to crack it on friday, also I'll be out tomorrow sorry.

2023-01-19 04:23 UTC, gigamonkey requested changes
Indeed, looks like you're on your way. this PR however has a ton of files from other projects in it. On Friday try to grab me so I can look at your codespace and see if we can clean this up a bit.

2023-01-19 23:32 UTC, AWalnut1 commented
Got lists working thank god. will actually write code tomorrow i swear

2023-01-20 23:34 UTC, AWalnut1 commented
got images working ahahahaha

2023-01-23 23:33 UTC, AWalnut1 commented
Almost done, got the links working put they are too large. 
also forgot to re request your review over the weekend sorry

2023-01-24 03:32 UTC, gigamonkey requested changes
Really close! I think you can find the problem with the hint I gave you. But if not I can give you some more hints in class. There are also some details you could fill in if you look at the HTML in `index.html` and the html you generated, e.g. the `li` elements don't just contain plain text. And the `img` element has another attribute.

Beyond that, the other thing to do with this assignment is to try to write some functions to reduce the amount of duplicated code. Of which there is necessarily a lot. Basically just find a few lines of code that you do wrote over and over with maybe just different values and wrap that up in a function and use it instead.

2023-01-24 03:32 UTC, gigamonkey commented on projects/2023-01-17/public/scripts/script.js
> +c1.append (h1)
If you inspect your page in the browser you'll see that you've created this structure:

![2023-01-23 at 7 23 PM](https://user-images.githubusercontent.com/250053/214206165-b3a5efb8-28dc-4259-88f2-78f6b03dcc56.png)

Notice how the `a` element is not in the `p` element represented here by `c2` which it should be. Can you see why?

2023-01-24 23:29 UTC, AWalnut1 commented
tried to make a helper function, didnt work out, commented it at the top of paragraph 2 so you can tell me how and why i messed it up. im just too tired right now to pursue this any further

2023-01-25 02:01 UTC, gigamonkey approved these changes
You hit all the main points. And I appreciate you trying to write a helper function, even if you didn't quite get it working in the time you had. You can merge this.

2023-01-25 22:32 UTC, AWalnut1 commented on projects/2023-01-17/public/scripts/script.js
> +//};
ah

2023-01-25 22:32 UTC, merged