Assignments/pig latin
bhs-intro-to-programming/AWalnut1 pull request #3
Opened 2022-09-19 22:33 UTC by AWalnut1

im not actually done or anything ive just been stuck on this and im sick of it, please help

-ben

2022-09-20 03:16 UTC, gigamonkey reviewed
Hopefully the comment I left gets you back on track? Ask me for help in class if not.

2022-09-20 03:16 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  var n = s.search(vowels);
So far so good (though I'd have written it as one expression like I did in the comment: `s.search(/[aeiou]/)`. But your way works too. After these two lines `n` will be a number, namely the index of the first vowel in `s`. So now you need to extract the back part of the string (i.e. starting from `n` and going to the end), the front part of the string (from 0 going to `n`) and then combine them, along with the string `'ay'`. If you recall from the string expressions exercises you should know how to do those parts.

2022-09-20 03:16 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  var n = s.search(vowels);
Also, don't use `var`. I'll talk about it in class some but it's a vestige of Javascript's early history. Just use `let` (or if a value is never going to change after it is assigned `const`.)

2022-09-20 21:34 UTC, AWalnut1 commented on assignments/pig-latin/code.js
> +  var n = s.search(vowels);
i know not to use var, i was just desperate for any kind of answer to what i was doing wrong at that point

2022-09-21 00:11 UTC, gigamonkey requested changes

2022-09-21 00:11 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  if n =
You may need to look at the Control constructs slides, starting here:

https://intro.gigamonkeys.com/slides/control-constructs/#/9

to get the scoop on `if`. Or you can look at the comments I left in the starter code here to see about how to use the ternary operator `?:`.

2022-09-22 03:17 UTC, gigamonkey reviewed
Looks like you're really close!

2022-09-22 03:17 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  return s.substring(s.length, n) + s.substring(0, n) + 'ay';
Lol. I thought this line was wrong because the arguments in `s.substring(s.length, n)` seem reversed because `s.length` is greater than `n`. But then I remembered that in Javascript if that's the case it just swaps them. Dunno if you knew that or just got lucky. I'd probably advise always writing them as start then end, i.e. the lower number first just because most people probably won't remember about the weird swapping behavior and because in most other languages that won't work in their equivalent to substring.

2022-09-22 03:17 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  return a === 0? "Zero" : "Not zero"
I saw you go on a journey through what I can guess was a bunch of frustration on the way here. But you're actually really close! Basically this structure is exactly right. Now you just need to replace the expression `"Zero"` with a different expression that returns the right answer in terms of `s` for when it starts with a vowel (i.e. tack on `'way'`) and then replace `"Not zero"` with an expression that returns the normal pig latin rules.

2022-09-22 22:18 UTC, AWalnut1 commented
hooray, finally done :)

2022-09-26 21:55 UTC, merged