getting started
bhs-intro-to-programming/AWalnut1 pull request #31
Opened 2023-01-26 23:34 UTC by AWalnut1

yep

2023-02-07 23:29 UTC, AWalnut1 commented
im gonna be completely honest with you, my brain is complete mush right now and i cannot focus enough to do any productive work, ill do work tomorrow i promise.

2023-02-07 23:29 UTC, AWalnut1 commented
also i ported the mouse tracking stuff i had on the laster version

2023-02-08 03:30 UTC, gigamonkey approved these changes
Are you planning to somehow combine the bus and the bouncing ball. Or should you go ahead and rip out the starter code that you don't need? Anyway, we should chat a bit about what your plan is. (Also, while I said you could have an extension, you may need to do some of that work outside of class because at some point soon we're going to do some new material during class which you'll need to pay attention to during class.)

2023-02-08 23:33 UTC, AWalnut1 commented
ill try to do soem stuff at home but no promises itl be any good

2023-02-09 23:33 UTC, AWalnut1 commented
on lines 94 on im trying to make a process to check if the bus is too close to the ball, but i didnt finish it in time. if you have any tips to make it work properly? also thanks for the help today xoxo.

2023-02-10 03:41 UTC, gigamonkey requested changes
A few small issues and then your distance detection should be working. Left comments to point you in the right direction.

2023-02-10 03:41 UTC, gigamonkey commented on projects/first-project/public/script.js
> +(distance(busX, ballX) + distance(busY, ballY))
Ah, this is where you gotta bust out the old pythagorean theorem. The distance between two points is the square root of the sum of the squares of the distances on each axis. Or you could import the `distance` function from the math functions I posted in https://classroom.google.com/c/NTM4MTI2Njk4MTQ4/m/NTkxNTA0NjgyNTM2/details and use that which will be easy because it does exactly what you need: compute the distance between two objects that both have `x` and `y` properties as the bus and ball both do.

2023-02-10 03:41 UTC, gigamonkey commented on projects/first-project/public/script.js
> +  if (distanceFromBall > 30) {
Note that `distanceFromBall` is a function so you need to call it with arguments, namely the x and y of both the bus and the ball.

2023-02-10 16:59 UTC, AWalnut1 commented on projects/first-project/public/script.js
> +};
im not sure if i would need to add arguments to this one as js says the ball and bus from the distanceFromBall inside the function are the same as the ones outside of it, so wouldnt that work for my purposes? or do i have to make some arguments for it to work properly?

2023-02-10 23:32 UTC, AWalnut1 commented
all i have left to do really is to make the score display in the html and not the console but i will also try to do some touch-ups to make it look more visually appealing and more fun

2023-02-13 18:40 UTC, AWalnut1 commented
Would have loved to make a high score feature but it seems i have not the knowledge at this time.
but hey look at thats its like almost a game that functions woaw!!!

2023-02-19 21:42 UTC, gigamonkey approved these changes
Approving this so you can merge it. Your grade will be posted in IC soon.

2023-02-21 22:35 UTC, merged