Assignments/hof implementation
bhs-intro-to-programming/AWalnut1 pull request #34
Opened 2023-02-28 23:31 UTC by AWalnut1

i am having issues with integrating the values into a single array in flatMap, any help?

2023-03-01 01:32 UTC, gigamonkey requested changes
Good progress! Keep on going and ask me for help tomorrow if you need more hints about `flatMap`.

2023-03-01 01:32 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +// i dont know what you mean by this
All of these functions could be trivially implemented by using the array method with the same name, e.g.:

```javascript
const filter = (predicate, array) => array.filter(predicate)
```

But I didn't want you to do that.

2023-03-01 01:32 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +    }//probably didnt need the if statement but im playing it safe here
No, you absolutely did. Otherwise this would add every element of the original array to the new array.

2023-03-01 01:32 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +    if (predicate(array[i]) === true) {
You don't need to compare a boolean value (such as that returned by `predicate`) to a literal as it's already a boolean. So you can just write:

```suggestion
    if (predicate(array[i])) {
```

2023-03-01 01:32 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +    productest.push(fn(array[i]))
I'll give you the hint I gave some other students. First make a variable that is the value returned by calling `fn`:

```javascript
    const subArray = fn(array[i]);
```

Now your task it to push each item from `subArray` onto `productest`, one at a time.

2023-03-01 22:33 UTC, AWalnut1 commented on assignments/hof-implementation/code.js
> +// i dont know what you mean by this
kinda funny

2023-03-01 23:32 UTC, AWalnut1 commented
thanks for the help

2023-03-01 23:33 UTC, AWalnut1 commented
the 'got' section is saying "Cannot access 'product' before initialization" on reduce, any idae why?

2023-03-02 01:11 UTC, gigamonkey requested changes
Some good progress. Some things to fix up in `reduce` and then you can tackle the rest.

2023-03-02 01:11 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +    for (let i = 0; i < subArray.length; i++) {
It doesn't matter here because there's no need to refer to the `i` from the outer loop in the inner loop but typically when we write nested loops we use differently named loop variables. Traditionally the outer loop uses `i` and if there's an inner loop, as here, it uses `j`.

2023-03-02 01:11 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +  array.unshift(initialValue) // i saw this on https://www.freecodecamp.org/news/how-to-insert-an-element-into-an-array-in-javascript/ i know you havent taught it to us but it works so nyeh
It does indeed work. However, in general, functions shouldn't modify their arguments unless that's part of the advertised purpose of the function. Suppose I had code like this:

```javascript
const total = reduce((a, b) => a + b, 0, mySpecialNumbers);
console.log(`The sum of my ${mySpecialNumbers.length) special numbers, the first of which is ${mySpecialNumbers[0]} is ${total}`);
```

I'd be kinda surprised when I called it with [17,42] and it logged:

```
The sum of my 3 special numbers, the first of which is 0, is 59.
```

rather than:

```
The sum of my 2 special numbers, the first of which is 17, is 59.
```

That said, this idea shows a good understanding of what we're trying to do here: the initialValue is like the first value of the array.

2023-03-02 01:11 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +    let product = product + fn(array[i])
This is not quite right since `fn` is supposed to be passed two values, the current value (which is initial value on the first time through the loop) and the array element and what it returns becomes the new current value; it's up to `fn` to add or multiply or whatever it does.

Also, the `let` here causes this to declare a new variable that hides the `product` you declared at the beginning of the function. (I suspect, actually, that Javascript complained about this line because you're referring to (the new) `product` before it is defined.

2023-03-02 22:36 UTC, AWalnut1 commented on assignments/hof-implementation/code.js
> +    for (let i = 0; i < subArray.length; i++) {
good to know

2023-03-02 23:18 UTC, AWalnut1 commented
yipee!!!!! finsh!!!!

2023-03-03 00:38 UTC, gigamonkey approved these changes
Looks good. Make sure you understand my comments about `reduce` but you`re good to merge.

2023-03-03 00:38 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +// these two are really easy i feel as if they should have gone first to ease us into this better, but im not the teacher
Hmmm, maybe. Kind of depends which things you remember, perhaps. But definitely `flatMap` and `reduce` are the hardest.

2023-03-03 00:38 UTC, gigamonkey commented on assignments/hof-implementation/code.js
> +  } // i feel as if less if statements are needed, if you would like to say how i could improve this code i would like you to
Your intuition is correct. A couple thoughts. One: whenever you are writing a function with this basic structure of initializing some value, looping and possibly updating the value, and then returning the value, one good question to ask yourself is, "Can I set the value at the beginning so it is the right answer if the loop runs zero times." You obviously recognized that if the loop doesn't run and `product` is still 0, then you want to return `initialValue` so why not just set `product` to `initialValue` at the beginning. That would get rid of the `if` at line 40. That would also let you get rid of the special case you have at line 36 because the line at line 39 would be correct for the first iteration because `product` would be the same as `initialValue` the first time through the loop, i.e. when `i` is 0. (Also, line 37 isn't really doing things right. If you did keep it, it should be something like:

```javascript
product = fn(initialValue, array[0]);
```

but, as you can probably see, that's basically just line 39, assuming `product` has the same value as `initialValue` and `i` is 0.

So, putting it all together, you have something like:

```javascript
const reduce = (fn, initialValue, array) => {
  let product = initialValue;
  for (let i = 0; i < array.length; i++) {
    product = fn(product, array[i]);
  }
  return product;
}
```

2023-04-24 22:01 UTC, merged