Assignments/array hofs
bhs-intro-to-programming/AWalnut1 pull request #35
Opened 2023-03-03 23:32 UTC by AWalnut1

very cool, will attempt to finish this over the weekend, but no promises.

2023-03-05 21:26 UTC, gigamonkey requested changes
What you've got here is looking good. Keep going.

2023-03-05 21:26 UTC, gigamonkey commented on assignments/array-hofs/code.js
> +//now that weve got the helper functions in lets go
You could also just use the array methods below. That's what I expected you to do.

2023-03-05 21:26 UTC, gigamonkey commented on assignments/array-hofs/code.js
> +  return reduce( (a,b) => (a+b / array.length), 0, map((n) => n.grade, array))
This is one where using the array methods as arguably easier to read because you can chain the calls:

```javascript
  return array.map((n) => n.grade).reduce((a, b) => a + b / array.length), 0);
```

I.e. map the array to just the grades and then reduce the array of grades. Reads left to right, the way we're used to in English.

2023-03-06 18:35 UTC, AWalnut1 commented
gonna be honest, totally forgot to do this over the weekend, sorry. Had some time to do it in first period but not much. I will probably ask for help with lengthOfNames in class later today unless some big epiphany comes my way.

2023-03-06 22:32 UTC, gigamonkey requested changes
More good code. We can chat about `lengthOfNames` today.

2023-03-06 22:32 UTC, gigamonkey commented on assignments/array-hofs/code.js
> +
These all look good.

2023-03-06 23:33 UTC, AWalnut1 commented
im going insane if i put 3 equals on the filter it returns empty but if i put 1 equals it gives the error Cannot assign to read only property '0' of string (first string in array) aAAAA

2023-03-07 23:31 UTC, AWalnut1 commented
its !== not ==!
otherwise pretty fun and challenging

2023-03-14 00:45 UTC, gigamonkey approved these changes
Bit late on my review but this all look good except for one small bug I commented on in `lengthOfNames`.

2023-03-14 00:45 UTC, gigamonkey commented on assignments/array-hofs/code.js
> +  return array.filter((n) => n !== n.toLowerCase()).map((n) => n.length)
This probably works on the tests I gave you but could fail if I have you strings like `"doesNotStartWithCapital"` which would not be weeded out by your `filter` function. You need something like `n[0] !== n[0].toLowerCase()` to check just the first character.

2023-04-24 22:02 UTC, merged