Assessments/unit 01
bhs-intro-to-programming/AWalnut1 pull request #4
Opened 2022-09-30 22:32 UTC by AWalnut1

im not done sorry (control constructs are hard:( )

2022-10-01 21:40 UTC, gigamonkey requested changes
Thanks for making a PR and giving me a chance to comment on some of the things you got confused by. You were far from the only student who had trouble with this assessment so I'm marking this "Request changes" as I'm going to have everyone who didn't finish the assessment (which is most people) do the rest of the problems but not as an assessment, i.e. you can ask questions or look back at the slides, etc.

2022-10-01 21:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +//  let Math.min (w, h) = smaller
Looks like you have one bit of confusion that made everything hard/impossible. The form of an assignment is:

```javascript
let variableYouAreDeclaring = valueYouWantItToHave;
```

For instance, this line was the right idea but you need to write it like:

```javascript
let smaller = Math.min(w, h);
```

That declares a new variable named `smaller` and initializes it to the value of the expression `Math.min(w, h)`, i.e. the smaller of the two values, which is exactly what you want.

2022-10-01 21:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +//  let a**2 + b**2 = c**2
You should read my comment at line 18 first because this has the same problem and then one other, namely, when you use a `let` you are declaring a variable not making a mathematical statement. So you could write this:

```javascript
let cSquared = a ** 2 + b ** 2;
```

And that would create a variable named `cSquared` with the value of the a squared plus b squared. You then need to take care of getting the square root of that yourself with something like:

```javascript
return Math.sqrt(cSquared);
```

2022-10-01 21:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +//  let w/r = circles
Same issue with let and assignment. If this was:

```javascript
let circles = w / r;
```

it would have in fact almost totally worked. (Almost because it actually needs to be `width / (r * 2)` because `r` is the radius, not the diameter.)

2022-10-01 21:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return senior || invited && !exclusion
This looks right however you and several other students got tripped up by order of operations. `&&` has higher precedence than `||` just like `*` has higher precedence than `+`. So this expression is evaluated as:

```javascript
isSenior || (invited && !onExclusionList)
```

Where the logic you want is:

```javascript
(isSenior || invited) && !onExclusionList
```

Of course, I'm pretty sure I never explicitly taught you about the relative precedence of these operators so it's not surprising that folks got tripped up.  One good rule of thumb is that if you're not sure about the relative precedence of different operators you can always put in parentheses to make the order of operations explicit.

2022-12-09 22:49 UTC, AWalnut1 commented
i did the things you asked of me, god thats a dumb mistake.i made back then

2022-12-10 01:18 UTC, gigamonkey approved these changes
Looks good. Ship it!

2022-12-12 23:27 UTC, merged