Assignments/recursion
bhs-intro-to-programming/AWalnut1 pull request #41
Opened 2023-04-10 22:31 UTC by AWalnut1

just doing what im doin

2023-04-11 22:33 UTC, AWalnut1 commented
uh yeah you know how it goes

2023-04-12 02:26 UTC, gigamonkey commented on assignments/recursion/code.js
> +    if (n - 1 === 0) {
Interesting. `n === 1` also works.

2023-04-12 02:27 UTC, gigamonkey commented on assignments/recursion/code.js
> +}; // im not touching this until i figure out what it even means
Yeah, this one seems to be throwing lots of folks for a loop. You can actually kinda just not worry about how it works and translate the English description into code. Or ask me if you're super stuck.

2023-04-12 22:32 UTC, AWalnut1 commented
started on reverseString, didnt have time to get very far though.

2023-04-13 03:24 UTC, gigamonkey requested changes
Good progress. A few small mistakes to fix, but otherwise keep on keeping on.

2023-04-13 03:24 UTC, gigamonkey commented on assignments/recursion/code.js
> +    return b;
This case is not wrong but it's also not necessary because if `a` is 0 then when we recurse `a % b` will be 0 and then what is now `b` will become `a` and will be returned.

2023-04-13 03:24 UTC, gigamonkey commented on assignments/recursion/code.js
> +}// this one is copied from the slides
smart.

2023-04-13 03:24 UTC, gigamonkey commented on assignments/recursion/code.js
> +    return 0
Mmmm. A reversed string should be a string so it can't be right to return a number here.

2023-04-13 03:24 UTC, gigamonkey commented on assignments/recursion/code.js
> +    return n.substring(0) + reverseString(n-1)
`n.substring(0)` is just a fancy way of making a new string that's the same as `n`. And `n - 1` doesn't make sense if `n` is a string.

2023-04-13 03:24 UTC, gigamonkey commented on assignments/recursion/code.js
> +    return a;
Erm, what's this line doing here?

2023-04-14 22:33 UTC, AWalnut1 commented
even though i did it im still not entirely sure how treeMap works, i just kinda got lucky on that one, can you explain it to me?

2023-04-15 23:54 UTC, gigamonkey approved these changes
Looks good. One nit about `reverseString` but otherwise looking good.

2023-04-15 23:54 UTC, gigamonkey commented on assignments/recursion/code.js
> +}; // i did not think that would work.
Surprise! Recursion is tricky that way sometimes.

2023-04-15 23:54 UTC, gigamonkey commented on assignments/recursion/code.js
> +  if (n.length === 1) {
This should really be `=== 0` so the function can handle the empty string properly.

2023-04-15 23:54 UTC, gigamonkey commented on assignments/recursion/code.js
> +}; // jaxon let me copy him for this one, very cool
Thanks for citing your sources! (It's fine to get help; just make sure you understand how it works so if you're called upon to write it again at some point, you can.)

2023-04-24 22:03 UTC, merged