Assignments/recursion 2
bhs-intro-to-programming/AWalnut1 pull request #42
Opened 2023-04-17 22:33 UTC by AWalnut1

i do not know how to do the multiply :(
i know its that when x starts as 0 it just returns y which is not right but i dont knwo how to fix :(

2023-04-18 03:32 UTC, gigamonkey requested changes
I'm going to talk in class about the approach you (and many others) took to `add` and `multiply` just because it's not quite what I was looking for even though it technically works here.

2023-04-18 03:32 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +}; // cannot beleive that worked
Yeah, a lot of folks write something like this which works, is technically recursive (i.e. it calls itself) but is not exactly in the spirit of how recursion normally works. What we want to do is head toward the base case by steps; this kind of jumps directly to the base case. I think I'm going to talk about this one in class since so many people did something along these lines.

2023-04-19 02:49 UTC, gigamonkey requested changes
Good start. Keep on going!

2023-04-19 02:49 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +};// what? i changed the base case to return 0 on a whim and it worked??? how???
So I didn't check what you had before but it's worth understanding why this is right: Certainly if `y` is zero the product of `x` and `y` has to be zero because anything times zero is zero. So that kind of settles what the base case has to be. And if you trace out the recursive calls you're going to end up with an expression like:

```
x + x + x + ... + x + 0
```

with `y` copies of `x` which is of course the same as `x * y + 0` which is the same as `x + y`.

2023-04-19 02:49 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +    return deleteXs(s.slice(1)) + s[0]
Close but you're sticking what used to be the first character of the string at the end. Why?

2023-04-19 22:32 UTC, AWalnut1 commented
i did everything but maximum by myslef

2023-04-20 02:59 UTC, gigamonkey approved these changes
Looks good!

2023-04-24 22:03 UTC, merged