Assignments/number function practice
bhs-intro-to-programming/AWalnut1 pull request #5
Opened 2022-10-05 23:02 UTC by AWalnut1

hey i forgot to make a pull request when i was there so im doing it now at home, i will continue this tomorrow but i think its good etiquette to submit it so you can see it
i believe the point of this assignment was to just fuck around so thats what i did, sorry if i misunderstood the directions.

2022-10-06 00:27 UTC, gigamonkey requested changes
Appreciate you making the PR. You definitely get the prize for the student who is making best use of PRs. I love your comments on your PRs and the way you actually use them to communicate and ask questions about things. Keep it up!

And indeed, the point of this assignment is to practice what you need to be ready for the new assessment this coming Friday. So I'm requesting changes only in the sense that you should keep practicing. In particular make sure you're comfortable going from a description of a function (or expression) and writing a function with the appropriate arguments to compute the desired result.

2022-10-06 00:27 UTC, gigamonkey commented on assignments/number-function-practice/code.js
> +}; // i dont understand why a function that takes two variables and returns thos two variables unchanged is so dang hard to program but it is
Yeah, the problem is you can only return one variable from a function. There are ways to package up multiple values into a single composite value but that's not quite the same as returning two values. So you're on an impossible mission with this one, sad to say.

2022-10-06 00:27 UTC, gigamonkey commented on assignments/number-function-practice/code.js
> +}; // i dont understand why a function that takes two variables and returns thos two variables unchanged is so dang hard to program but it is
For what it's worth, this is a legal function but it always returns the value of `b`. This is because in this context the `,` is actually an operator that says, evaluate the first expression `(a)` and throw away the result and then evaluate the second expression `(b)` and make that the value of the `,` expression. But that's a pretty useless operator so it's almost never used except by accident.

2022-10-06 21:34 UTC, AWalnut1 commented on assignments/number-function-practice/code.js
> +}; // i dont understand why a function that takes two variables and returns thos two variables unchanged is so dang hard to program but it is
this is so sad

2022-10-06 22:33 UTC, AWalnut1 commented
not sure if theres a way to create a secondary pull request but i think just writing a comment works just fine

2022-12-09 22:54 UTC, AWalnut1 commented
there are ways to package up multiple values into a single composite value
also no idea why i didnt merge this back in october but i guess that let me finally (almost) fill out my dream of the nothing function

2022-12-10 01:20 UTC, gigamonkey approved these changes
LGTM. Ship It!

2022-12-12 23:28 UTC, merged